import { AssetProps, GENDER } from "../../type/type";

export const hairs: AssetProps[] = [
    {name: 'Court 1', key: 'short_1', gender: GENDER.FEMALE, assets: 'assets/textures/hairs/female/court.png'},
    {name: 'Court 2', key: 'short_2', gender: GENDER.FEMALE, assets: 'assets/textures/hairs/female/court_2.png'},
    {name: 'Court 3', key: 'short_3', gender: GENDER.FEMALE, assets: 'assets/textures/hairs/female/court_3.png'},
    {name: 'Court 4', key: 'short_4', gender: GENDER.FEMALE, assets: 'assets/textures/hairs/female/court_4.png'},
    {name: 'Court 5', key: 'short_5', gender: GENDER.FEMALE, assets: 'assets/textures/hairs/female/court_2.png'},
    {name: 'Très Long 1', key: 'extralong_1', gender: GENDER.FEMALE, assets: 'assets/textures/hairs/female/extra_long.png'},
    {name: 'Très Long 2', key: 'extralong_2', gender: GENDER.FEMALE, assets: 'assets/textures/hairs/female/extra_long_2.png'},
    {name: 'Très Long 3', key: 'extralong_3', gender: GENDER.FEMALE, assets: 'assets/textures/hairs/female/extra_long_3.png'},
    {name: 'Très Long 4', key: 'extralong_4', gender: GENDER.FEMALE, assets: 'assets/textures/hairs/female/extra_long_4.png'},
    {name: 'Très Long 5', key: 'extralong_5', gender: GENDER.FEMALE, assets: 'assets/textures/hairs/female/extra_long_5.png'},
    {name: 'Long 1', key: 'long_1', gender: GENDER.FEMALE, assets: 'assets/textures/hairs/female/long.png'},
    {name: 'Calvitie 1', key: 'calvitie_1', gender: GENDER.MALE, assets: 'assets/textures/hairs/male/calvitie_1.png'},
    {name: 'Calvitie 2', key: 'calvitie_2', gender: GENDER.MALE, assets: 'assets/textures/hairs/male/calvitie_2.png'},
    {name: 'Calvitie 3', key: 'calvitie_3', gender: GENDER.MALE, assets: 'assets/textures/hairs/male/calvitie_3.png'},
    {name: 'Calvitie 4', key: 'calvitie_4', gender: GENDER.MALE, assets: 'assets/textures/hairs/male/calvitie_4.png'},
    {name: 'Calvitie 5', key: 'calvitie_5', gender: GENDER.MALE, assets: 'assets/textures/hairs/male/calvitie_5.png'},
    {name: 'Calvitie 6', key: 'calvitie_6', gender: GENDER.MALE, assets: 'assets/textures/hairs/male/calvitie_6.png'},
    {name: 'Crète 1', key: 'crete_1', gender: GENDER.MALE, assets: 'assets/textures/hairs/male/crete.png'},
    {name: 'Chauve 1', key: 'chauve_1', gender: GENDER.MALE, assets: 'assets/textures/hairs/male/chauve.png'},
    {name: 'Dégradé 1', key: 'degrade_1', gender: GENDER.MALE, assets: 'assets/textures/hairs/male/degrade.png'},
    {name: 'Dreadlocks 1', key: 'dreadlocks_1', gender: GENDER.MALE, assets: 'assets/textures/hairs/male/dreadlocks.png'},
    {name: 'Long 1', key: 'long_1', gender: GENDER.MALE, assets: 'assets/textures/hairs/male/long.png'},
    {name: 'Long 2', key: 'long_2', gender: GENDER.MALE, assets: 'assets/textures/hairs/male/long_2.png'},
    {name: 'Long 3', key: 'long_3', gender: GENDER.MALE, assets: 'assets/textures/hairs/male/long_3.png'},
    {name: 'Long 4', key: 'long_4', gender: GENDER.MALE, assets: 'assets/textures/hairs/male/long_4.png'},
    {name: 'Long 5', key: 'long_5', gender: GENDER.MALE, assets: 'assets/textures/hairs/male/long_5.png'},
    {name: 'Moyen 1', key: 'mid_1', gender: GENDER.MALE, assets: 'assets/textures/hairs/male/mid.png'},
    {name: 'Moyen 2', key: 'mid_2', gender: GENDER.MALE, assets: 'assets/textures/hairs/male/mid_2.png'},
    {name: 'Moyen 3', key: 'mid_3', gender: GENDER.MALE, assets: 'assets/textures/hairs/male/mid_3.png'},
    {name: 'Moyen 4', key: 'mid_4', gender: GENDER.MALE, assets: 'assets/textures/hairs/male/mid_4.png'},
    {name: 'Moyen 5', key: 'mid_5', gender: GENDER.MALE, assets: 'assets/textures/hairs/male/mid_5.png'},
    {name: 'Moyen 6', key: 'mid_6', gender: GENDER.MALE, assets: 'assets/textures/hairs/male/mid_6.png'},
    {name: 'Mi long 1', key: 'mid_long_1', gender: GENDER.MALE, assets: 'assets/textures/hairs/male/mid_long.png'},
    {name: 'Mi long 2', key: 'mid_long_2', gender: GENDER.MALE, assets: 'assets/textures/hairs/male/mid_long_2.png'},
    {name: 'Mi long 3', key: 'mid_long_3', gender: GENDER.MALE, assets: 'assets/textures/hairs/male/mid_long_3.png'},
    {name: 'Mi long 4', key: 'mid_long_4', gender: GENDER.MALE, assets: 'assets/textures/hairs/male/mid_long_4.png'},
    {name: 'Court 1', key: 'short_1', gender: GENDER.MALE, assets: 'assets/textures/hairs/male/short.png'},
    {name: 'Court 2', key: 'short_2', gender: GENDER.MALE, assets: 'assets/textures/hairs/male/short_2.png'},
    {name: 'Court 3', key: 'short_3', gender: GENDER.MALE, assets: 'assets/textures/hairs/male/short_3.png'},
    {name: 'Court 4', key: 'short_4', gender: GENDER.MALE, assets: 'assets/textures/hairs/male/short_4.png'},
    {name: 'Très Long 1', key: 'extralong_1', gender: GENDER.MALE, assets: 'assets/textures/hairs/male/extra_long.png'},
];

export const hairColors = [
    '#FFD6A9',
    '#E3A86F',
    '#D38138',
    '#FFEEB9',
    '#F6D059',
    '#F5B31A',
    '#965C29',
    '#AC5300',
    '#783200',
    '#D6D6D6',
    '#918D98',
    '#4F4A55',
    '#F29159',
    '#9E3D3B',
    '#584B39',
    '#FF8746',
    '#FF6000',
    '#DF3800',
    '#2F2E2E',
    '#FFF392',
    '#FFE700',
    '#FFE3F8',
    '#FFB0E0',
    '#3A1705',
    '#774320',
    '#CC8B33',
    '#E5BA6A',
    '#F4D987',
    '#71584A',
    '#AC8964',
    '#333333',
    '#111111',
  ];